services:
  - type: web
    name: spyweb-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: MONGODB_URI
        value: mongodb+srv://spywebtech:eI9OkqExPla99zFB@cluster0.fxmwfzf.mongodb.net/spyweb_db?retryWrites=true&w=majority
      - key: PORT
        value: 5000
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        value: abhisudame1@gmail.com
      - key: EMAIL_PASSWORD
        value: cxwglksywicuqlsl
      - key: ADMIN_EMAIL
        value: abhisudame1@gmail.com
